### PR TITLE
linux-hardkernel: Use SKIP_RECIPE varflag

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
wait for master-next changes in oe-core to land into master before merging this patch.

**Comment by akuster** [comment]
its in master-next. I will wait for it to hit master.

**Comment by kraj** [comment]
Can we merge this pull please @akuster, the relevant changes in oe-core are in master

**Comment by akuster** [comment]
thanks

**Pull request merged**
