### PR TITLE
Add support for odroid-m1

### PR DESCRIPTION
**Pull request by rmsc**
Everything's done except u-boot, which at this point is being built for a different board (evb_rk3568).

The m1 does come with u-boot and petitboot in an onboard SPI flash, so building a working u-boot isn't actually needed to get the board running.

### CODE REVIEW

**Comment by akuster** [comment]
thanks. I reviewing your changes and doing a test build.  Does this boot?

**Comment by rmsc** [comment]
It does, yes. I've been booting daily from the NVME, via petitboot.

Booting from the EMMC should work using the embedded (but outdated) u-boot directly. I confess I haven't tested in a while, but can do it next week.

**Comment by rmsc** [comment]
Sorry for the long delay, I just got around to test booting from the EMMC and it's broken.

It seems that the default `UBOOT_ROOT` from the `*.bbclass` is taking precedence over the machine defaults, which is wrong.

Since this PR is already merged (thanks!), I'll close it and create a new one for the fix. Sorry..

**Comment by rmsc** [comment]
Turns out it was a simple fix, created a new PR.

I'm not allowed to close this as "merged", @akuster could you please do it? Thanks!

**Comment by akuster** [comment]
Opps sorry. Yeah I did it manually.
Thanks for adding the M1 support

**Pull request closed without merging**
