### PR TITLE
mesa-gl: Remove KHR/khrplatform.h for mali + mali

### PR DESCRIPTION
**Pull request by kraj**
Its needed for general meson-gx platforms not only for odroid-c4 machine since there are other C4 variant machines too e.g. odroid-c4-hardkernel

### CODE REVIEW

**Comment by akuster** [comment]
changes under test

**Comment by akuster** [comment]
I am getting the original  build failure on odroid-c2:

https://errors.yoctoproject.org/Errors/Build/175148/

I was wondering if defining GPU in the MACHINE_OVERRIDES would be an option.

**Comment by kraj** [comment]
> I am getting the original build failure on odroid-c2:
> 
> https://errors.yoctoproject.org/Errors/Build/175148/
> 
> I was wondering if defining GPU in the MACHINE_OVERRIDES would be an option.

yeah I added a check for ` PREFERRED_PROVIDER_virtual/gpu`

**Comment by kraj** [comment]
> > I am getting the original build failure on odroid-c2:
> > https://errors.yoctoproject.org/Errors/Build/175148/
> > I was wondering if defining GPU in the MACHINE_OVERRIDES would be an option.
> 
> yeah I added a check for ` PREFERRED_PROVIDER_virtual/gpu` hope this fixed c2 issue you are seeing

**Comment by akuster** [comment]
ok, I will test this updated version. thanks,

**Comment by akuster** [comment]
ok, lgtm.

merging

**Pull request closed without merging**
